var quotes = [
    "Attention, ce flim n’est pas un flim sur le cyclimse. Merci de votre compréhension.",
    "Entre l’Australia et la South América, dans l’océan South Pacific : l’atoll de Pom Pom Galli.",
    "— V12 appelle le capitaine George Abitbol, V12 appelle le capitaine George Abitbol. Quelqu’un vous demande sur le pont.\n— Qui ?\n— Un dénommé José.\n— OK, j’arrive, V12.",
    "Ah, voilà enfin le roi de la classe ! L’homme trop bien sapé, Abitbol !",
    "Alors comme ça tu as été élu l’homme le plus classe du monde ! Laisse-moi rire !",
    "Style le grand play-boy des fonds marins, genre qui fait rêver les ménagères. Sauf que moi je les baise, moi, les ménagères, non ? C’est pas vrai ?",
    "Écoute-moi bien, mon petit José. Tu baises les ménagères, bien, tu dois avoir le cul qui brille. Mais c’est pas ça qu’on appelle la classe.",
    "Je te dis ça en qualité d’homme le plus classe du monde.",
    "Eh, je t’arrête tout de suite. La classe, c’est d’être chic dans sa manière de s’habiller.",
    "Rien de tel que d’aller chez Azzedine Alaia… ou même de s’acheter des sous-pulls chez Yohji Yamamoto !",
    "Excuse-moi de te dire ça, mon pauvre José, mais tu confonds un peu tout.",
    "Tu fais un amalgame entre la coquetterie et la classe. Tu es fou.",
    "Tu dépenses tout ton argent dans les habits et accessoires de mode mais tu es ridicule. Enfin si ça te plaît…",
    "C’est toi qui les portes. Mais moi, si tu veux mon opinion, ça fait un peu… has been.",
    "La vache !",
    "Moi, j’ai l’air has been ?",
    "J’en ai pour plus d’une barre de fringues sur moi. Alors, va te faire mettre !",
    "Tu n’es vraiment pas très sympa. Mais le train de tes injures roule sur le rail de mon indifférence.",
    "Je préfère partir plutôt que d’entendre ça plutôt que d’être sourd.",
    "Bien ! Considère qu’on n’est plus amis, Abitbol !",
    "Tiens, regarde ! Les Anglais ont débarqué. On va être obligés de passer par derrière. Tu sais, par ce tunnel tout sombre qui sent pas très bon.",
    "Oh, George ! Quel poète, vous me surprenez. On ne m’a jamais parlé comme ça. J’ai connu des hommes, mais jamais des comme vous !",
    "— Eh, tu sais à qui tu parles, là ?\n— Oui !",
    "— Abritons-nous, ça va pas tarder à péter !\n— Oh, et encore c’est rien !\n— Classe, bravo. Bon, pousse-toi, laisse-moi passer.",
    "— Bon V12 c’est quoi ce bordel alors ?\n— Ben ce bordel c’est qu’il pleut comme vache qui pisse !\n— Ah bravo, merci du renseignement.\n— Heureusement que tu es là.",
    "V12 — Mais patron !\n— Quoi patron ? Tu veux que je dise à tout le monde que ton vrai nom c’est pas V12 c’est travers de porc sel-poivre ?",
    "Bon, je vais chercher des serviettes-éponges avec des imprimés dessus. Ah, celle-là. Non. Celle-là… Ah, celle-là, ça va.",
    "Ça, c’est bon, c’est épongé.\nÇa, c’est bon, c’est réparé.\nÇa, ça roule.",
    "Oh putain et ça ? Faut pas laisser ça comme ça les enfants !",
    "George ! George ! Oh mon Dieu George ! Oh ! Oh !",
    "Aah… Monde de merde.",
    "Oh George…",
    "Et puis je vous rappelle la principale information de cette édition, la disparition subite de George Abitbol, qui depuis plus de 15 ans portait officiellement le titre de l’homme le plus classe du monde.\nL’Amérique vient de perdre un de ses plus prestigieux ambassadeurs.",
    "— Et maintenant, un petit peu de musique avec Alain Souchon.\n— Oh non, pas lui ! (Il éteint la radio.)",
    "Salopes !",
    "— Bonjour patron, je peux entrer ?\n— Ah Dave, tu tombes bien. Entre.",
    "On prépare un dossier sur George Abitbol. Tu vas te mettre sur le coup, mais tu seras pas tout seul, tu seras avec Peter et Steven.",
    "Peter et Steven, je les aime bien. Mais pourquoi je peux pas travailler seul ?",
    "— Parce que tu es trop mauvais.\n— Ah ben là patron vous m’avez convaincu, c’est une bonne raison.",
    "— Je vais travailler avec Peter et Steven.",
    "— Ben alors ?",
    "— Ben OK, j’y vais.",
    "Ce charlot ? Je savais pas qu’il existait encore.",
    "Va falloir vous y habituer parce qu’il va travailler avec vous sur ce dossier. C’est une idée de notre ami Callaghan.\nUne idée lumineuse !",
    "Roh arrêtez vos conneries, patron. C’est mon fils, mon fiston. Pff.",
    "Je sais pas pourquoi, il s’est attaché à moi. Alors, je l’aide.",
    "Ben peut-être qu’il avait personne d’autre à qui s’attacher. Mais de quoi on parle ?",
    "Je vais te dire de quoi on parle.\nOù vous en êtes avec la nécro de George Abitbol ?\nVous bossez un peu ?\nMmh ?",
    "On vient de s’y mettre, mais on a déjà quelques petites idées.",
    "On va interroger des tas de gens, tous ceux qui l’ont aimé, qui l’ont haï, bref tous ceux qui l’ont approché qui l’ont connu. Ça fait déjà du boulot."
]
